name: msys2-fpm

on:
  push:
    paths:
    - "app/**.f90"
    - "src/**.f90"
    - "test/**.f90"
    - "fpm.toml"
    
  pull_request:
    branches:
    - main
    paths:
    - "app/**.f90"
    - "src/**.f90"
    - "test/**.f90"
    - "fpm.toml"

jobs:
  build:
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
        
    steps:
      - uses: actions/checkout@v2
      - uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW64
          update: true
          install: |
            git
            mingw-w64-x86_64-gcc-fortran 
            mingw-w64-x86_64-gcc-libgfortran 
            mingw-w64-x86_64-fpm
            
      - name: fpm build
        run: |
          fpm build
          